CONTAINER C4DMX
{
	NAME C4DMX;
    INCLUDE Texpression;

    GROUP ID_TAGPROPERTIES
	{
		REAL C4DMX_UNIVERSE {MIN 0.0; STEP 1;}
		REAL C4DMX_BASE_ADDRESS {MIN 0.0; MAX 512.0; STEP 1;}
		BOOL C4DMX_ISMASTER {}
		BOOL C4DMX_USETARGET {}
		BOOL C4DMX_EXPORT {}
		REAL C4DMX_EXPORTLOW {MIN 0.0;STEP 1;}
		REAL C4DMX_EXPORTHIGH {MIN 0.0;STEP 1;}
		STRING C4DMX_EXPORTPATH {}
		REAL C4DMX_EXPORTBPM {MIN 0.0;}

	}
}
